-- 공공API
CREATE TABLE TM_CAMPINGZONE
(
    IDX NUMBER(5) PRIMARY KEY,
    CPNAME VARCHAR2(40),
    CPTEL VARCHAR2(20),
    LAT NUMBER(20),
    LNG NUMBER(20),
    ADDR VARCHAR2(100)
);

-- 공공API
select * from TM_CAMPINGZONE_CHONGCHUNG;
CREATE TABLE TM_CAMPINGZONE_CHONGCHUNG
(
IDX NUMBER(5) PRIMARY KEY,
CPNAME VARCHAR2(100),
CPTEL VARCHAR2(20),
LAT NUMBER(20),
LNG NUMBER(20),
ADDR VARCHAR2(100),
cpLineIntro VARCHAR2(100), 
cpLctCl VARCHAR2(100), 
cpPosblFcltyCl VARCHAR2(100), 
cpHomepage VARCHAR2(100), 
cpAnimalCmgCl VARCHAR2(100), 
cpInduty VARCHAR2(100)
);

select * from TM_CAMPINGZONE_EXAL